### ISSUE TITLE
Error with markdown-it

### ISSUE THREAD

**Issue by ghost** [vkbansal/illuminate-js#2]
Hello there,

I'm playing with illuminate and markdown-it, but following your example, I got this error message in the console : `Error: A grammar must have an _order array`.

Any idea ?

Regards

**Comment by vkbansal** [comment]
Can you tell which language are you trying to highlight?

Try this code to find out:

``` js
var illuminate = require('illuminate-js')

var md = require('markdown-it')({
  highlight: function (str, lang) {
    console.log(lang);
    if (lang && illuminate.getLanguage(lang)) {
        return illuminate.highlight(lang, str);
    }

    return '';
  }
});
```

**Comment by ghost** [comment]
Hi,
This is the code I use, then, calling this:

`````` js
md.render('### Title\n```javascript\nvar someVar = \'foo\'```\n');
``````

will log `js` but still trigger the error.

**Comment by vkbansal** [comment]
Can you put the code you are using. I'm unable to reproduce the error.

**Comment by ghost** [comment]
Hi, sorry for the delay

Here's my real code:

`````` javascript
var illuminate = require('illuminate-js'),
    md = require('markdown-it');

var mdOptions = {
    highlight: function (str, lang) {
        console.log(lang);
        if (lang && illuminate.getLanguage(lang)) {
            return illuminate.highlight(lang, str);
        }

        return '';
    },
};
var parser = md(mdOptions);

parser.render('### Title\n```javascript\nvar someVar = \'foo\'```\n');

``````

Outputs:

```
javascript
/Users/dreadcast/Sites/md/node_modules/illuminate-js/lib/index.js:33
        throw new Error("A grammar must have an _order array");
        ^

Error: A grammar must have an _order array
    at tokenize (/Users/dreadcast/Sites/md/node_modules/illuminate-js/lib/index.js:33:15)
    at Object.highlight (/Users/dreadcast/Sites/md/node_modules/illuminate-js/lib/index.js:127:18)
    at Object.mdOptions.highlight (/Users/dreadcast/Sites/md/index.js:8:22)
    at Object.default_rules.fence (/Users/dreadcast/Sites/md/node_modules/markdown-it/lib/renderer.js:43:27)
    at Renderer.render (/Users/dreadcast/Sites/md/node_modules/markdown-it/lib/renderer.js:292:38)
    at MarkdownIt.render (/Users/dreadcast/Sites/md/node_modules/markdown-it/lib/index.js:513:24)
    at Object.<anonymous> (/Users/dreadcast/Sites/md/index.js:16:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
27 Feb 12:29:37 - [nodemon] app crashed - waiting for file changes before starting...
```

Same result with this : 

`````` javascript
var illuminate = require('illuminate-js')

var md = require('markdown-it')({
  highlight: function (str, lang) {
    console.log(lang);
    if (lang && illuminate.getLanguage(lang)) {
        return illuminate.highlight(lang, str);
    }

    return '';
  }
});

md.render('### Title\n```javascript\nvar someVar = \'foo\'```\n');
``````

Node version: 4.0.0
markdown-it: 4.4.0
illuminate-js: 0.2.0

**Comment by vkbansal** [comment]
OKAY!! Now I get it! Sorry it's my fault.

Actually `illuminate.highlight(lang, str)` must be `illuminate.highlight(str, lang)`.

I've update the README too.

Thanks for reporting!!

**Comment by ghost** [comment]
It works now!
I should have read the doc :)
